apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: mongodb-deployment
      labels:
        app: mongodb

    spec:
      serviceAccountName: foo

      containers:
      - image: docker.io/mongo
        name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      - name: ambassador
        image: luksa/kubectl-proxy:1.6.2
      - name: main
        image: tutum/curl
        command: ["sleep", "9999999"]

      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: pvc01